CREATE TABLE pais (
                      id_pais INT PRIMARY KEY,
                      nm_pais VARCHAR2(50) NOT NULL
);

CREATE TABLE estado (
                        id_estado INT PRIMARY KEY,
                        nm_estado VARCHAR2(50) NOT NULL,
                        id_pais INT NOT NULL,
                        CONSTRAINT estado_pais_fk FOREIGN KEY (id_pais)
                            REFERENCES pais(id_pais)
);

CREATE TABLE cidade (
                        id_cidade INT PRIMARY KEY,
                        nm_cidade VARCHAR2(50) NOT NULL,
                        id_estado INT NOT NULL,
                        CONSTRAINT cidade_estado_fk FOREIGN KEY (id_estado)
                            REFERENCES estado(id_estado)
);

CREATE TABLE bairro (
                        id_bairro INT PRIMARY KEY,
                        nm_bairro VARCHAR2(50) NOT NULL,
                        id_cidade INT NOT NULL,
                        CONSTRAINT bairro_cidade_fk FOREIGN KEY (id_cidade)
                            REFERENCES cidade(id_cidade)
);

CREATE TABLE endereco (
                          id_endereco INT PRIMARY KEY,
                          nm_rua VARCHAR2(100) NOT NULL,
                          nr_numero VARCHAR2(10),
                          id_bairro INT NOT NULL,
                          CONSTRAINT endereco_bairro_fk FOREIGN KEY (id_bairro)
                              REFERENCES bairro(id_bairro)
);

CREATE TABLE patio (
                       id_patio INT PRIMARY KEY,
                       nm_patio VARCHAR2(100) NOT NULL,
                       id_endereco INT NOT NULL,
                       CONSTRAINT patio_endereco_fk FOREIGN KEY (id_endereco)
                           REFERENCES endereco(id_endereco)
);

CREATE TABLE operador (
                          id_operador INT PRIMARY KEY,
                          nm_operador VARCHAR2(100) NOT NULL,
                          cargo_operador VARCHAR2(50),
                          id_patio INT NOT NULL,
                          CONSTRAINT operador_patio_fk FOREIGN KEY (id_patio)
                              REFERENCES patio(id_patio)
);

CREATE TABLE modelo (
                        id_modelo INT PRIMARY KEY,
                        nm_modelo VARCHAR2(100) NOT NULL,
                        mt_tipo VARCHAR2(50)
);

CREATE TABLE moto (
                      id_moto INT PRIMARY KEY,
                      mt_placa VARCHAR2(10) NOT NULL,
                      mt_status VARCHAR2(20),
                      id_modelo INT NOT NULL,
                      CONSTRAINT moto_modelo_fk FOREIGN KEY (id_modelo)
                          REFERENCES modelo(id_modelo)
);

CREATE TABLE manutencao (
                            id_manutencao INT PRIMARY KEY,
                            dt_manutencao DATE NOT NULL,
                            ds_servico VARCHAR2(200),
                            id_moto INT NOT NULL,
                            CONSTRAINT manutencao_moto_fk FOREIGN KEY (id_moto)
                                REFERENCES moto(id_moto)
);

CREATE TABLE setor (
                       id_setor INT PRIMARY KEY,
                       nm_setor VARCHAR2(100) NOT NULL,
                       id_patio INT NOT NULL,
                       CONSTRAINT setor_patio_fk FOREIGN KEY (id_patio)
                           REFERENCES patio(id_patio)
);

CREATE TABLE mapa_setor (
                            id_mapa INT PRIMARY KEY,
                            ds_mapa VARCHAR2(200),
                            id_setor INT NOT NULL,
                            id_patio INT NOT NULL,
                            CONSTRAINT mapa_setor_setor_fk FOREIGN KEY (id_setor)
                                REFERENCES setor(id_setor),
                            CONSTRAINT mapa_setor_patio_fk FOREIGN KEY (id_patio)
                                REFERENCES patio(id_patio)
);

CREATE TABLE movimentacao (
                              id_mov INT PRIMARY KEY,
                              dt_mov DATE NOT NULL,
                              id_moto INT NOT NULL,
                              id_setor INT NOT NULL,
                              id_operador_origem INT NOT NULL,
                              id_operador_destino INT,
                              CONSTRAINT mov_moto_fk FOREIGN KEY (id_moto) REFERENCES moto(id_moto),
                              CONSTRAINT mov_setor_fk FOREIGN KEY (id_setor) REFERENCES setor(id_setor),
                              CONSTRAINT mov_operador_ori_fk FOREIGN KEY (id_operador_origem) REFERENCES operador(id_operador),
                              CONSTRAINT mov_operador_des_fk FOREIGN KEY (id_operador_destino) REFERENCES operador(id_operador)
);

CREATE TABLE auditoria_movimentacao (
                                        id_auditoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        usuario VARCHAR2(100),
                                        operacao VARCHAR2(10),
                                        data_hora TIMESTAMP DEFAULT SYSTIMESTAMP,
                                        valores_old VARCHAR2(4000),
                                        valores_new VARCHAR2(4000)
);
