CREATE TABLE pais (
    id_pais BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_pais VARCHAR(50) NOT NULL
);

CREATE TABLE estado (
    id_estado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_estado VARCHAR(50) NOT NULL,
    id_pais BIGINT NOT NULL,
    CONSTRAINT estado_pais_fk FOREIGN KEY (id_pais)
        REFERENCES pais(id_pais)
);

CREATE TABLE cidade (
    id_cidade BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_cidade VARCHAR(50) NOT NULL,
    id_estado BIGINT NOT NULL,
    CONSTRAINT cidade_estado_fk FOREIGN KEY (id_estado)
        REFERENCES estado(id_estado)
);

CREATE TABLE bairro (
    id_bairro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_bairro VARCHAR(50) NOT NULL,
    id_cidade BIGINT NOT NULL,
    CONSTRAINT bairro_cidade_fk FOREIGN KEY (id_cidade)
        REFERENCES cidade(id_cidade)
);

CREATE TABLE endereco (
    id_endereco BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_rua VARCHAR(100) NOT NULL,
    nr_numero VARCHAR(10),
    id_bairro BIGINT NOT NULL,
    CONSTRAINT endereco_bairro_fk FOREIGN KEY (id_bairro)
        REFERENCES bairro(id_bairro)
);

CREATE TABLE patio (
    id_patio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_patio VARCHAR(100) NOT NULL,
    id_endereco BIGINT NOT NULL,
    CONSTRAINT patio_endereco_fk FOREIGN KEY (id_endereco)
        REFERENCES endereco(id_endereco)
);

CREATE TABLE operador (
    id_operador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_operador VARCHAR(100) NOT NULL,
    cargo_operador VARCHAR(50),
    id_patio BIGINT NOT NULL,
    CONSTRAINT operador_patio_fk FOREIGN KEY (id_patio)
        REFERENCES patio(id_patio)
);

CREATE TABLE modelo (
    id_modelo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_modelo VARCHAR(100) NOT NULL,
    mt_tipo VARCHAR(50)
);

CREATE TABLE moto (
    id_moto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mt_placa VARCHAR(10) NOT NULL,
    mt_status VARCHAR(20),
    id_modelo BIGINT NOT NULL,
    CONSTRAINT moto_modelo_fk FOREIGN KEY (id_modelo)
        REFERENCES modelo(id_modelo)
);

CREATE TABLE manutencao (
    id_manutencao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_manutencao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ds_servico VARCHAR(200),
    id_moto BIGINT NOT NULL,
    CONSTRAINT manutencao_moto_fk FOREIGN KEY (id_moto)
        REFERENCES moto(id_moto)
);

CREATE TABLE setor (
    id_setor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_setor VARCHAR(100) NOT NULL,
    id_patio BIGINT NOT NULL,
    CONSTRAINT setor_patio_fk FOREIGN KEY (id_patio)
        REFERENCES patio(id_patio)
);

CREATE TABLE mapa_setor (
    id_mapa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ds_mapa VARCHAR(200),
    id_setor BIGINT NOT NULL,
    id_patio BIGINT NOT NULL,
    CONSTRAINT mapa_setor_setor_fk FOREIGN KEY (id_setor)
        REFERENCES setor(id_setor),
    CONSTRAINT mapa_setor_patio_fk FOREIGN KEY (id_patio)
        REFERENCES patio(id_patio)
);

CREATE TABLE movimentacao (
    id_mov BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_mov TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_moto BIGINT NOT NULL,
    id_setor BIGINT NOT NULL,
    id_operador_origem BIGINT NOT NULL,
    id_operador_destino BIGINT,
    CONSTRAINT mov_moto_fk FOREIGN KEY (id_moto) REFERENCES moto(id_moto),
    CONSTRAINT mov_setor_fk FOREIGN KEY (id_setor) REFERENCES setor(id_setor),
    CONSTRAINT mov_operador_ori_fk FOREIGN KEY (id_operador_origem) REFERENCES operador(id_operador),
    CONSTRAINT mov_operador_des_fk FOREIGN KEY (id_operador_destino) REFERENCES operador(id_operador)
);

CREATE TABLE auditoria_movimentacao (
    id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(100),
    operacao VARCHAR(10),
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    valores_old TEXT,
    valores_new TEXT
);
